version: '2'
services:

  web:
    # image: gitea/gitea:1.7.1
    build: ./Gitea
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "2233:22"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=gitea
    volumes:
      - ./db/:/var/lib/postgresql/data

  drone:
    image: drone/drone:1
    ports:
      - 8000:80
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    depends_on:
      - web
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=http://165.22.200.132:3000
      - DRONE_RPC_SECRET=q3r8GhcyUA2MF5shMhLWUntz
      - DRONE_SERVER_HOST=165.22.200.132:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true

    # to use mysql uncomment following
    # image: mariadb:10
    # restart: always
    # environment:
    #   - MYSQL_ROOT_PASSWORD=changeme
    #   - MYSQL_DATABASE=gitea
    #   - MYSQL_USER=gitea
    #   - MYSQL_PASSWORD=changeme
    # volumes:
    #   - ./db/:/var/lib/mysql