version: '2'

networks:
  web:
    external: true

services:

  # Traefik section
  # Reverse proxy
  traefik:
    image: traefik  # The official Traefik docker image
    command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    restart: always
    networks:
    - web
    ports:
    - "80:80"
    - "443:443"
    # - "9000:9000"  # exposes the Traefik web UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # So that Traefik can listen to the Docker events
      - "./config/traefik.toml:/traefik.toml"
      - "./config/acme.json:/acme.json"
    container_name: traefik

  # GITEA Section
  # Source Code versioning with CI
  web:
    # image: gitea/gitea:1.7.1
    build: ./services/Gitea
    volumes:
      - ./volumes/data/:/data
    networks:
      - web
    ports:
      # - "3000:3000"
      - "2233:22"
    depends_on:
      - db
    restart: always
    labels:
      - "traefik.frontend.rule=Host:dev.maymeow.io"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.protocol=http"

  db:
    image: postgres
    restart: always
    networks:
      - web
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data

  drone:
    image: drone/drone:1.1
    networks:
      - web
    ports:
      # - 8000:80
      - 9000:9000
    volumes:
      - ./volumes/drone/:/var/lib/drone
    restart: always
    depends_on:
      - web
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=https://dev.maymeow.io
      - DRONE_RPC_SECRET=q3r8GhcyUA2MF5shMhLWUntz
      - DRONE_SERVER_HOST=drone.maymeow.io
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
    labels:
      - "traefik.frontend.rule=Host:drone.maymeow.io"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.protocol=http"

    # to use mysql uncomment following
    # image: mariadb:10
    # restart: always
    # environment:
    #   - MYSQL_ROOT_PASSWORD=changeme
    #   - MYSQL_DATABASE=gitea
    #   - MYSQL_USER=gitea
    #   - MYSQL_PASSWORD=changeme
    # volumes:
    #   - ./db/:/var/lib/mysql